version: "3"
services:
  jupyter:
    build: .
    entrypoint:
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebookdir=/workspace
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/app/workspace
